spring:
  datasource:
    url: jdbc:mysql://114.67.106.207:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: james
    password: james2020+
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 实体类扫描路径
  type-aliases-package: com.james.sample.mybatis.annotation.entity
  # xml 扫描路径
   mapper-locations: classpath:mapper/*.xml
